### ISSUE TITLE
support directory of images in WallPaper plugin

### ISSUE THREAD

**Issue by kfirufk** [compiz-reloaded/compiz-plugins-extra#4]
Hi.
I'd like to have the ability to add a directory of images instead of one image after the other in the Wallpaper plugin.
if that directory can be monitored so it will auto detect when I add or remove images from it, that would be cool :) thanks

**Comment by ShadowKyogre** [comment]
This sounds pretty neat! It maybe a bit overkill if you have a huge wallpaper collection. A few questions about how this would work:

* What order are the images loaded in for the wallpaper plugin, should we implement this? I'm going to presume by name since that's the most stable ordering.
* This takes over all of the wallpaper loading, correct? Would there be a case where you'd only want the directory to cover some of the viewports? (( eg: 1-4 covered by folder, 5-9 are individually picked ))
* Randomized wallpapers from the directory? It's the first thing I thought of when you mentioned that.

Though, I think better approach to this problem (( except if a user for some reason does have something like 1024 viewports )) would be to have a way to batch add images to the backgrounds list.

Thoughts, @soreau and @XRevan86?

**Comment by kfirufk** [comment]
Hi. it would be net to set a images scan limit in the options menu.. so if the user has too many images it will take the first 200 or 300 images. or even to add an option to add the images in random order. so for example if i have 2000 images, and i set the config to load 200. so every couple of months click on the plugin, rescan randomly and voila.. different 200-300 images.

**Comment by soreau** [comment]
@ShadowKyogre In response to the bullet points you made:
- I think the default should be by name with option to randomize
- No, I don't think it would 'take over all of the wallpaper loading'. We should still preserve the case of adding a single file at a time.
- Yes, I think randomize should be an option.
I'm not exactly sure what you mean by 'batch add images to the backgrounds list'. I think the implementation would be the same as what we have now, additionally with a way to add a directory and option to randomize the entire list (regardless if it came from a directory or listed as a single file).

@kfirufk I don't think we should worry about limits for now, perhaps something like this could potentially be implemented as a separate option.

**Comment by soreau** [comment]
After looking at the code a bit, it seems that the config system would need require some rework to support directories and files in the same list, so it's looking like the simplest way will be to have two lists, one for single files and one for directories. It isn't the most elegant end result but compizconfig system isn't exactly the most elegant thing, and it would be the simplest way to make this happen.

**Comment by ShadowKyogre** [comment]
@soreau : 
For the second bullet, what I meant was, "If directory loading is in effect, should we ignore individual wallpapers for the viewports?" My fingers didn't type it out correctly the first time.

For batch add images to the backgrounds list, what I meant was the following interaction sequence:

0. User has a bunch of pictures that they know they want to set as their wallpapers.
0. These pictures are not in sequential order name wise. They also know that they want them all scaled.
0. They open a file dialog and select the pictures they want to load.
0. Those files get added to the wallpaper list with their position pre-set to scaled.

Theoretically, the special case mentioned above could just be handled with a script written specifically for configuring the wallpaper plugin since it might be one of those niche cases.

The current UI to accomplish the same thing flows like this:

0. Create new element
0. Open edit dialog
0. Open image filepicker
0. Pick image
0. Set position type to scaled
0. Repeat previous steps for each wallpaper, so many clicks.

**Comment by soreau** [comment]
@ShadowKyogre
Regarding the second bullet: No, we shouldn't ignore the singular list if directory list != NULL. I'm thinking internally (in wallpaper.c) we could probably put them all in the same list and handle them internally same as how it works currently. The only difference would be that the directory entries would all have the same position, fill type and color settings.

For the batch case, unless I'm misunderstanding you, the directory list will make this a non-issue.

**Comment by soreau** [comment]
Initial implementation: https://github.com/soreau/wallpaper
Run `make && make install` as user and the plugin will be installed to ~/.compiz/
Apply this ccsm patch for directory button: http://sprunge.us/YLQZ
Restart compiz and ccsm

There is no special emphasis placed on the file ordering btw, they are ordered by wherever they are placed in the list in ccsm and if a directory, ordered by `man readdir`. This code is pretty complicated but seems to work well in local testing. Please test and leave your comments here.

**Comment by soreau** [comment]
Upstreamed.
