### ISSUE TITLE
scalefilter: Window manager: Backspace filters for 0x08 instead of removing the previous character

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz-plugins-extra#8]
It would be nice to backspace in scalefilter.

**Comment by SergioGeeK7** [comment]
same. I'm using compiz 0.8.14

**Comment by soreau** [comment]
There is code to handle this case [here](https://github.com/compiz-reloaded/compiz-plugins-extra/blob/master/src/scalefilter/scalefilter.c#L453) but it is broken because [this](https://github.com/compiz-reloaded/compiz-plugins-extra/blob/master/src/scalefilter/scalefilter.c#L417) always returns NoSymbol for some reason and it isn't obvious why yet.

**Comment by soreau** [comment]
Can either of you try [this patch](https://gist.github.com/soreau/6d9f05b6b92ab209fa48711a234f1e0a)? It changes the group from 1 to 0 and seems to work here.

**Comment by ethus3h** [comment]
That patch fixes the issue! Thanks!

**Comment by SergioGeeK7** [comment]
wow, this is big news, question, should I make the change and recompile and install compiz-plugins-extra ?

**Comment by soreau** [comment]
@SergioGeeK7 You can either apply it manually or get latest git, the [patch](https://github.com/compiz-reloaded/compiz-plugins-extra/commit/39c1544e81a39797b606edf29eb2cab00f3a9f30) has been applied.
